### ISSUE TITLE
Nuxt 3 support

### ISSUE THREAD

**Issue by hacknug** [nuxt-community/ackee-module#15]
Any plans on adding support for Nuxt 3? I looked into porting it myself but I'm not familiar enough with the module architecture for v3 yet 🤷‍♂️

**Comment by lihbr** [comment]
Hey there, thanks for your interest in Nuxt Ackee module!

To be completely transparent - as one of the maintainers of this module - I've stopped using Ackee with Nuxt 3 and I wasn't planning on porting the module to it.

Looking at the code, things should be pretty straightforward though! The main update would have to happen on the plugins side of things.

If you feel like creating a PR and learning a few things along the way, I'm very happy to help you throughout that endeavor! Here's how I'd go to start that project:
1. [Fork the repository](https://github.com/nuxt-community/ackee-module/fork)
2. Get the Nuxt 3 module boilerplate with `npx nuxi init -t module ackee` (this will copy the files in a new `ackee` folder)
3. From here you can work on porting the Nuxt 2 module to the Nuxt 3 module in the `ackee` folder. [The module guide](https://v3.nuxtjs.org/guide/going-further/modules) can help you, especially [the examples](https://v3.nuxtjs.org/guide/going-further/modules#provide-nuxt-plugins). TypeScript should also be really useful
4. Push and open a PR

No pressure of course! If you don't have time, feel like it's too complex, or you're just not interested, it's all perfectly fine! Let me know and I'll try to free up some time to perform that migration~

**Comment by harlan-zw** [comment]
Will track here: https://github.com/nuxt-community/ackee-module/issues/20 :)
